export { usersReducer } from './model/users.reducer'
export { getUsers, setFollow, setUnfollow } from './model/thunks/users.thunks'
export { setCurrentPage } from './model/actions/users.actions'
export { getUsersState } from './model/selectors/getUsersState'
export type { UsersST, ProgressFollowT, UserT } from './types/users.reducer'
