name: building, testing, linting
run-name: ${{ github.actor }} is testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.16.1 ]
        
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: build production
        run: CI=false yarn build
        if: always()
      - name: linting es
        run: yarn lint:es
        if: always()
      - name: linting styles
        run: yarn lint:sc
        if: always()
      - name: testing unit
        run: yarn test
        if: always()
